[package]
name = "informalsystems-malachitebft-proto"
description = "Protobuf abstraction for the Malachite BFT consensus engine"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
readme = "../../../README.md"

[package.metadata.docs.rs]
all-features = true

[dependencies]
prost.workspace = true
prost-types.workspace = true
thiserror.workspace = true
