[package]
name = "informalsystems-malachitebft-signing-ed25519"
description = "Ed25519 signing scheme for the Malachite BFT consensus engine"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true
readme = "../../../README.md"

[package.metadata.docs.rs]
all-features = true

[features]
std = []
serde = ["dep:serde", "dep:base64"]
rand = ["dep:rand"]

[dependencies]
malachitebft-core-types = { workspace = true }

signature = { workspace = true }
ed25519-consensus = { workspace = true }

# Optional dependencies
rand = { workspace = true, optional = true }   # rand
serde = { workspace = true, optional = true }  # serde
base64 = { workspace = true, optional = true } # serde

[lints]
workspace = true
