[alias]
mbt         = "nextest run -p malachite-itf --all-features --no-fail-fast"
integration = "nextest run --workspace --exclude malachite-itf --no-fail-fast"
unit-tests  = "nextest run --workspace --all-features --no-fail-fast --failure-output final --exclude informalsystems-malachitebft-test --exclude informalsystems-malachitebft-test-mbt --exclude informalsystems-malachitebft-starknet-test --exclude informalsystems-malachitebft-starknet-test-mbt --exclude informalsystems-malachitebft-discovery-test"
