[package]
name                   = "malachite-starknet-p2p-types"
version.workspace      = true
edition.workspace      = true
repository.workspace   = true
license.workspace      = true
rust-version.workspace = true
publish                = false

[dependencies]
malachite-core-types.workspace = true
malachite-proto.workspace = true
malachite-starknet-p2p-proto.workspace = true

starknet-core.workspace = true
starknet-crypto.workspace = true

bytes.workspace = true
rand.workspace = true
serde.workspace = true
sha3.workspace = true

[lints]
workspace = true
