[package]
name = "informalsystems-malachitebft-starknet-p2p-types"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
malachitebft-core-types.workspace = true
malachitebft-proto.workspace = true
malachitebft-starknet-p2p-proto.workspace = true

starknet-core.workspace = true
starknet-crypto.workspace = true

bytes.workspace = true
rand.workspace = true
serde.workspace = true
sha3.workspace = true

[lints]
workspace = true
