[package]
name                 = "malachite-gossip-mempool"
version.workspace    = true
edition.workspace    = true
repository.workspace = true
license.workspace    = true
publish.workspace    = true

[lints]
workspace = true

[dependencies]
malachite-metrics = { workspace = true }
malachite-proto   = { workspace = true }

futures           = { workspace = true }
libp2p            = { workspace = true }
prost             = { workspace = true }
prost-types       = { workspace = true }
seahash           = { workspace = true }
tokio             = { workspace = true, features = ["macros"] }
tracing           = { workspace = true }

[build-dependencies]
prost-build.workspace = true
