[workspace]
resolver = "2"

members = [
  "crates/actors",
  "crates/cli",
  "crates/common",
  "crates/consensus",
  "crates/driver",
  "crates/gossip-consensus",
  "crates/gossip-mempool",
  "crates/metrics",
  "crates/node",
  "crates/proto",
  "crates/round",
  "crates/test",
  "crates/test/mbt",
  "crates/vote",
  "crates/starknet/*"
]

[workspace.package]
version      = "0.1.0"
edition      = "2021"
repository   = "https://github.com/informalsystems/malachite"
license      = "Apache-2.0"
publish      = false
rust-version = "1.77"

[profile.release]
overflow-checks = true

[profile.profiling]
inherits = "release"
debug = true

[workspace.lints.rust]
unused_crate_dependencies = "warn"

[workspace.dependencies]
malachite-actors           = { version = "0.1.0", path = "crates/actors" }
malachite-cli              = { version = "0.1.0", path = "crates/cli" }
malachite-common           = { version = "0.1.0", path = "crates/common" }
malachite-consensus        = { version = "0.1.0", path = "crates/consensus" }
malachite-driver           = { version = "0.1.0", path = "crates/driver" }
malachite-gossip-consensus = { version = "0.1.0", path = "crates/gossip-consensus" }
malachite-gossip-mempool   = { version = "0.1.0", path = "crates/gossip-mempool" }
malachite-test-mbt         = { version = "0.1.0", path = "crates/test/mbt" }
malachite-metrics          = { version = "0.1.0", path = "crates/metrics" }
malachite-node             = { version = "0.1.0", path = "crates/node" }
malachite-proto            = { version = "0.1.0", path = "crates/proto" }
malachite-round            = { version = "0.1.0", path = "crates/round" }
malachite-test             = { version = "0.1.0", path = "crates/test" }
malachite-vote             = { version = "0.1.0", path = "crates/vote" }

# Starknet
malachite-starknet-host      = { version = "0.1.0", path = "crates/starknet/host" }
malachite-starknet-app       = { version = "0.1.0", path = "crates/starknet/app" }
malachite-starknet-p2p-proto = { version = "0.1.0", path = "crates/starknet/p2p-proto" }
malachite-starknet-p2p-types = { version = "0.1.0", path = "crates/starknet/p2p-types" }

# Starknet
starknet-core   = "0.11.1"
starknet-crypto = "0.7.1"

async-recursion    = "1.1"
async-trait        = "0.1.82"
axum               = "0.7"
base64             = "0.22.0"
bytesize           = "1.3"
bytes              = "1"
clap               = "4.5"
color-eyre         = "0.6"
config             = { version = "0.14", features = ["toml"], default-features = false }
derive-where       = "1.2.7"
directories        = "5.0.1"
ed25519-consensus  = "2.1.0"
either             = "1"
eyre               = "0.6"
futures            = "0.3"
genawaiter         = { version = "0.99.1", default-features = false }
glob               = "0.3.0"
hex                = { version = "0.4.3", features = ["serde"] }
humantime          = "2.1.0"
humantime-serde    = "1.1.1"
itertools          = "0.13"
itf                = "0.2.3"
libp2p             = { version = "0.54.1", features = ["macros", "identify", "tokio", "ed25519", "ecdsa", "tcp", "quic", "noise", "yamux", "gossipsub", "dns", "ping", "metrics"] }
libp2p-identity    = "0.2.9"
libp2p-broadcast   = { version = "0.12.0", git = "https://github.com/romac/libp2p-broadcast.git" }
multiaddr          = "0.18.2"
num-bigint         = "0.4.4"
num-traits         = "0.2.17"
pretty_assertions  = "1.4"
prometheus-client  = "0.22"
prost              = "0.13"
prost-build        = "0.13"
prost-types        = "0.13"
ractor             = "0.11.2"
ractor_actors      = { version = "0.4.2", default-features = false }
rand               = { version = "0.8.5", features = ["std_rng"] }
rand_chacha        = "0.3.1"
seahash            = "4.1"
serde              = "1.0"
serde_json         = "1.0"
serde_with         = "3.9"
sha3               = "0.10"
signature          = "2.2.0"
tempfile           = "3.12.0"
thiserror          = "1.0"
tokio              = "1.40.0"
tokio-stream       = "0.1"
toml               = "0.8.19"
tikv-jemallocator  = "0.6.0"
tracing            = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
