#######################################################################
###                   Main Base Config Options                      ###
#######################################################################

# The name of the application to runtime
# Available values: starknet, test
# Override with MALACHITE__APP env variable
app = "starknet"

# A custom human readable name for this node
# Override with MALACHITE__MONIKER env variable
moniker = "malachite"

#######################################################
###          Logging Configuration Options          ###
#######################################################
[logging]
# The application log level.
# Override with MALACHITE__LOGGING__LOG_LEVEL env variable.
# See more: https://docs.rs/env_logger/latest/env_logger/#enabling-logging
log_level = "debug"

# The log format.
# Possible values:
# - "plaintext": log entries are in colorful text
# - "json": log entries are presented as JSON objects
# Override with MALACHITE__LOGGING__LOG_FORMAT env variable.
log_format = "plaintext"


#######################################################
###         Consensus Configuration Options         ###
#######################################################
[consensus]
# Maximum block size
# Override with MALACHITE__CONSENSUS__MAX_BLOCK_SIZE env variable
max_block_size = "1 MiB"

## Timeouts
# How long we wait for a proposal block before prevoting nil
# Override with MALACHITE__CONSENSUS__TIMEOUT_PROPOSE env variable
timeout_propose = "3s"

# How much timeout_propose increases with each round
timeout_propose_delta = "500ms"

# How long we wait after receiving +2/3 prevotes for “anything” (ie. not a single block or nil)
# Override with MALACHITE__CONSENSUS__TIMEOUT_PREVOTE env variable
timeout_prevote = "1s"

# How much the timeout_prevote increases with each round
timeout_prevote_delta = "500ms"

# How long we wait after receiving +2/3 precommits for “anything” (ie. not a single block or nil)
# Override with MALACHITE__CONSENSUS__TIMEOUT_PRECOMMIT env variable
timeout_precommit = "1s"

# How much the timeout_precommit increases with each round
timeout_precommit_delta = "500ms"

# How long we wait after committing a block, before starting on the new
# height (this gives us a chance to receive some more precommits, even
# though we already have +2/3).
# Override with MALACHITE__CONSENSUS__TIMEOUT_COMMIT env variable
timeout_commit = "0s"

#######################################################
###       Consensus P2P Configuration Options       ###
#######################################################
[consensus.p2p]

# Address to listen for incoming connections
listen_addr = "/ip4/0.0.0.0/udp/0/quic-v1"

# List of nodes to keep persistent connections to
persistent_peers = []

# The type of pub-sub protocol to use for consensus
# Possible values:
# - "gossipsub": Use the GossipSub v1.1 protocol (gossip, recommended)
# - "broadcast": Use the Broadcast protocol (no gossip, experimental)
# Override with MALACHITE__CONSENSUS__P2P__PROTOCOL env variable
protocol = "gossipsub"


#######################################################
###          Mempool Configuration Options          ###
#######################################################
[mempool]

# Maximum number of transactions in the mempool
# Override with MALACHITE__MEMPOOL__MAX_TX_COUNT env variable
max_tx_count = 10000

# Maximum number of transactions to gossip at once in a batch.
# If set to 0, mempool does not gossip the transactions.
# Override with MALACHITE__MEMPOOL__GOSSIP_BATCH_SIZE
gossip_batch_size = 0

#######################################################
###       Mempool P2P Configuration Options       ###
#######################################################
[mempool.p2p]

# Address to listen for incoming connections
listen_addr = "/ip4/0.0.0.0/udp/0/quic-v1"

# List of nodes to keep persistent connections to
persistent_peers = []

# The type of pub-sub protocol to use for the mempool
# /!\ This setting has no effect on the mempool yet /!\
#
# Possible values:
# - "gossipsub": Use the GossipSub v1.1 protocol (gossip, recommended)
# - "broadcast": Use the Broadcast protocol (no gossip, experimental)
# Override with MALACHITE__CONSENSUS__MEMPOOL__PROTOCOL env variable
protocol = "gossipsub"

#######################################################
###          Metrics Configuration Options          ###
#######################################################
[metrics]

# Enable the metrics server
enabled = true

# Metrics are exported at `http://127.0.0.1:9000/metrics`
listen_addr = "127.0.0.1:9000"

#######################################################
###          Runtime Configuration Options          ###
#######################################################
[runtime]

# The flavor of Tokio runtime to use.
# Possible values:
# - "single_threaded": A single threaded runtime (default)
# - "multi_threaded":  A multi-threaded runtime
flavor = "single_threaded"

# For the multi-threaded runtime only.
# Sets the number of worker threads the Runtime will use.
# If set to 0, defaults to the number of cores available to the system.
# worker_threads = 4


#######################################################
###          Test Node Configuration Options         ###
#######################################################
[test]

# Override with MALACHITE__TEST__TX_SIZE env variable
tx_size = "1 KiB"
# Override with MALACHITE__TEST__TXS_PER_PART env variable
txs_per_part = 256
# Override with MALACHITE__TEST__TIME_ALLOWANCE_FACTOR env variable
time_allowance_factor = 0.5
# Override with MALACHITE__TEST__EXEC_TIME_PER_TX env variable
exec_time_per_tx = "1ms"
