[package]
name                   = "malachite-node"
version.workspace      = true
edition.workspace      = true
repository.workspace   = true
license.workspace      = true
publish.workspace      = true
rust-version.workspace = true

[dependencies]
malachite-common.workspace  = true

rand  = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
