[package]
name                   = "malachite-starknet-app"
version.workspace      = true
edition.workspace      = true
repository.workspace   = true
license.workspace      = true
rust-version.workspace = true
publish                = false

[lints]
workspace = true

[dependencies]
malachite-test-cli = { workspace = true }
malachite-config = { workspace = true }
malachite-starknet-host = { workspace = true }

color-eyre = { workspace = true }
tracing = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemallocator = { workspace = true, features = ["background_threads"] }

[dev-dependencies]
clap = { workspace = true }
tempfile = { workspace = true }
