[package]
name                   = "malachite-starknet-app"
version.workspace      = true
edition.workspace      = true
repository.workspace   = true
license.workspace      = true
publish.workspace      = true
rust-version.workspace = true

[dependencies]
malachite-actors.workspace             = true
malachite-blocksync.workspace          = true
malachite-common.workspace             = true
malachite-consensus.workspace          = true
malachite-gossip-consensus.workspace   = true
malachite-gossip-mempool.workspace     = true
malachite-metrics.workspace            = true
malachite-config.workspace             = true
malachite-node.workspace               = true
malachite-proto.workspace              = true
malachite-starknet-host.workspace      = true
malachite-starknet-p2p-proto.workspace = true
malachite-starknet-p2p-types.workspace = true
malachite-test.workspace               = true

async-trait.workspace                  = true
bytesize.workspace                     = true
libp2p-identity.workspace              = true
prost.workspace                        = true
rand.workspace                         = true
serde.workspace                        = true
serde_json.workspace                   = true
tokio.workspace                        = true
tracing-subscriber.workspace           = true
tracing.workspace                      = true

# [lints]
# workspace = true
