[package]
name = "informalsystems-malachitebft-engine"
description = "Implementation of the Malachite BFT consensus engine"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true
readme = "../../../README.md"

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[dependencies]
malachitebft-codec.workspace = true
malachitebft-config.workspace = true
malachitebft-core-consensus.workspace = true
malachitebft-core-types.workspace = true
malachitebft-network.workspace = true
malachitebft-metrics.workspace = true
malachitebft-sync.workspace = true
malachitebft-wal.workspace = true

async-trait = { workspace = true }
bytes = { workspace = true, features = ["serde"] }
byteorder = { workspace = true }
derive-where = { workspace = true }
eyre = { workspace = true }
libp2p = { workspace = true }
ractor = { workspace = true, features = ["async-trait"] }
rand = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
