[package]
name                   = "malachite-test-app"
version.workspace      = true
edition.workspace      = true
repository.workspace   = true
license.workspace      = true
publish.workspace      = true
rust-version.workspace = true

[dependencies]
malachite-actors.workspace           = true
malachite-common.workspace           = true
malachite-driver.workspace           = true
malachite-node.workspace             = true
malachite-metrics.workspace          = true 
malachite-gossip-consensus.workspace = true
malachite-gossip-mempool.workspace   = true
malachite-test.workspace             = true
malachite-proto.workspace            = true

async-trait.workspace                = true
bytesize.workspace                   = true
derive-where.workspace               = true
tokio.workspace                      = true
tracing.workspace                    = true

[dev-dependencies]
malachite-test     = { workspace = true }
rand               = { workspace = true }
rand_chacha        = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }

[lints]
# workspace = true
