[package]
name = "informalsystems-malachitebft-network"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
malachitebft-discovery = { workspace = true }
malachitebft-metrics = { workspace = true }
malachitebft-peer = { workspace = true }
malachitebft-sync = { workspace = true }

bytes = { workspace = true }
either = { workspace = true }
eyre = { workspace = true }
futures = { workspace = true }
libp2p = { workspace = true }
libp2p-broadcast = { workspace = true }
seahash = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
