[package]
name = "informalsystems-malachitebft-discovery"
description = "Discovery protocol for the Malachite BFT consensus engine"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
readme = "../../../README.md"

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[dependencies]
malachitebft-metrics = { workspace = true }
libp2p = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
either = { workspace = true }
rand = { workspace = true }
