[package]
name        = "malachite-round"
description = "Per-round state-machine for the Malachite consenss engine"

version.workspace      = true
edition.workspace      = true
repository.workspace   = true
license.workspace      = true
publish.workspace      = true
rust-version.workspace = true

[dependencies]
malachite-common = { version = "0.1.0", path = "../common" }

derive-where.workspace = true
displaydoc.workspace   = true
time                   = { workspace = true, optional = true }

[features]
std = []
debug = ["std", "dep:time"]
