[package]
name = "informalsystems-malachitebft-metrics"
description = "Metrics for the Malachite BFT consensus engine"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[package.metadata.docs.rs]
all-features = true

[dependencies]
malachitebft-core-state-machine.workspace = true
prometheus-client.workspace = true

[lints]
workspace = true
