[package]
name                   = "malachite-metrics"
version.workspace      = true
edition.workspace      = true
repository.workspace   = true
license.workspace      = true
publish.workspace      = true
rust-version.workspace = true

[dependencies]
malachite-round.workspace   = true
prometheus-client.workspace = true

[lints]
workspace = true
