[package]
name                   = "malachite-starknet-host"
version.workspace      = true
edition.workspace      = true
repository.workspace   = true
license.workspace      = true
rust-version.workspace = true
publish                = false

[dependencies]
malachite-actors = { workspace = true }
malachite-app = { workspace = true }
malachite-codec = { workspace = true }
malachite-config = { workspace = true }
malachite-consensus = { workspace = true, features = ["debug"] }
malachite-core-types = { workspace = true }
malachite-network = { workspace = true }
malachite-metrics = { workspace = true }
malachite-node = { workspace = true }
malachite-proto = { workspace = true }
malachite-starknet-p2p-proto = { workspace = true }
malachite-starknet-p2p-types = { workspace = true }
malachite-sync = { workspace = true }
malachite-test-mempool = { workspace = true }

async-trait = { workspace = true }
bytes = { workspace = true, features = ["serde"] }
bytesize = { workspace = true }
derive-where = { workspace = true }
eyre = { workspace = true }
itertools = { workspace = true }
libp2p-identity = { workspace = true }
prost = { workspace = true }
ractor = { workspace = true }
rand = { workspace = true }
redb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
malachite-cli.workspace = true
