[package]
name                   = "malachite-starknet-host"
version.workspace      = true
edition.workspace      = true
repository.workspace   = true
license.workspace      = true
publish.workspace      = true
rust-version.workspace = true

[dependencies]
malachite-actors.workspace             = true
malachite-blocksync.workspace          = true
malachite-consensus.workspace          = true
malachite-gossip-consensus.workspace   = true
malachite-common.workspace             = true
malachite-metrics.workspace            = true
malachite-node.workspace               = true
malachite-config.workspace             = true
malachite-gossip-mempool.workspace     = true
malachite-proto.workspace              = true
malachite-starknet-p2p-types.workspace = true
malachite-starknet-p2p-proto.workspace = true

bytes = { workspace = true, features = ["serde"] }

starknet-core.workspace   = true
async-trait.workspace     = true
bytesize.workspace        = true
derive-where.workspace    = true
itertools.workspace       = true
libp2p-identity.workspace = true
eyre.workspace            = true
prost.workspace           = true
ractor.workspace          = true
rand.workspace            = true
redb.workspace            = true
sha3.workspace            = true
serde_json.workspace      = true
tokio.workspace           = true
tracing.workspace         = true
thiserror.workspace       = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
malachite-cli.workspace = true