[package]
name = "informalsystems-malachitebft-starknet-host"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
malachitebft-engine = { workspace = true }
malachitebft-app = { workspace = true }
malachitebft-codec = { workspace = true }
malachitebft-config = { workspace = true }
malachitebft-core-consensus = { workspace = true, features = ["debug"] }
malachitebft-core-types = { workspace = true }
malachitebft-network = { workspace = true }
malachitebft-metrics = { workspace = true }
malachitebft-proto = { workspace = true }
malachitebft-starknet-p2p-proto = { workspace = true }
malachitebft-starknet-p2p-types = { workspace = true }
malachitebft-sync = { workspace = true }
malachitebft-test-mempool = { workspace = true }

async-trait = { workspace = true }
bytes = { workspace = true, features = ["serde"] }
bytesize = { workspace = true }
config = { workspace = true }
derive-where = { workspace = true }
eyre = { workspace = true }
itertools = { workspace = true }
libp2p-identity = { workspace = true }
prost = { workspace = true }
ractor = { workspace = true }
rand = { workspace = true }
redb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha3 = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
malachitebft-test-cli.workspace = true
