[package]
name = "malachite-app"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
malachite-actors.workspace = true
malachite-codec.workspace = true
malachite-core-types.workspace = true
malachite-config.workspace = true
malachite-consensus.workspace = true
malachite-network.workspace = true
malachite-metrics.workspace = true
malachite-peer.workspace = true
malachite-sync.workspace = true

async-trait = { workspace = true }
eyre = { workspace = true }
libp2p-identity = { workspace = true }
rand  = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
