[package]
name                   = "malachite-starknet-host"
version.workspace      = true
edition.workspace      = true
repository.workspace   = true
license.workspace      = true
publish.workspace      = true
rust-version.workspace = true

[dependencies]
malachite-actors.workspace = true
malachite-common.workspace = true
malachite-test.workspace   = true
malachite-proto.workspace  = true

async-trait.workspace     = true
bytesize.workspace        = true
derive-where.workspace    = true
eyre.workspace            = true
itertools.workspace       = true
prost.workspace           = true
ractor.workspace          = true
signature.workspace       = true
sha2.workspace            = true
subtle-encoding.workspace = true
tokio.workspace           = true
tracing.workspace         = true

[build-dependencies]
prost-build.workspace = true

[lints]
workspace = true
