{
 "title": "Malachite first stab",
 "time": { "from": "2024-07-05T06:25:19.000Z", "to": "2024-07-05T06:45:37.000Z" },
 "panels": [
  { "title": "Transactions and blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total number of blocks created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "malachite_consensus_finalized_blocks_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks created every minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(malachite_consensus_finalized_blocks_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total number of transactions created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "malachite_consensus_finalized_txes_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transactions created every minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(malachite_consensus_finalized_txes_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Round",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "malachite_consensus_round", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Round buckets (count / round)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(malachite_consensus_rounds_per_block_bucket[$__rate_interval])) by (le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average time for block creation over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "malachite_consensus_time_per_block_sum/malachite_consensus_time_per_block_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block creation buckets (count / creation time)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(malachite_consensus_time_per_block_bucket[$__rate_interval])) by (le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block size over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "malachite_consensus_block_size_bytes_sum/malachite_consensus_block_size_bytes_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WIP Block size buckets (count / size in bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(malachite_consensus_block_size_bytes_bucket{le=\"8323072.0\"}[$__rate_interval])) by (instance)/sum(rate(malachite_consensus_block_size_bytes_count[$__rate_interval])) by (instance)",
     "legendFormat": "Bytes"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Current Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    { "expr": "malachite_consensus_height", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Number of connected peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "malachite_consensus_connected_peers",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}