services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 127.0.0.1:9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus

  grafana:
    # image: grafana/grafana-oss
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 127.0.0.1:3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_LOG_LEVEL: info
      GF_ANALYTICS_ENABLED: false
      GF_ANALYTICS_REPORTING_ENABLED: false
      GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: false
      GF_ANALYTICS_CHECK_FOR_UPDATES: false
      GF_ANALYTICS_FEEDBACK_LINKS_ENABLED: false
      GF_SECURITY_DISABLE_GRAVATAR: true
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards-data/malachite.json
      GF_DASHBOARDS_MIN_REFRESH_INTERVAL: 1s
      GF_USERS_DEFAULT_THEME: system
      GF_USERS_EDITORS_CAN_ADMIN: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_AUTH_BASIC_ENABLED: false
      GF_NEWS_NEWS_FEED_ENABLED: false
