volumes:

  logs:
    driver: local
    driver_opts:
      type: none
      device: ./logs
      o: bind

  config:
    driver: local
    driver_opts:
      type: none
      device: ./config
      o: bind

  build:
    driver: local
    driver_opts:
      type: none
      device: ./build
      o: bind

  malachite:
    driver: local
    driver_opts:
      type: none
      device: ../../code
      o: bind

  sequencer:
    driver: local
    driver_opts:
      type: none
      device: ../../../sequencer
      o: bind

networks:

  test-network:
    driver: bridge

services:

  malachite-node-1:
    container_name: malachite-node-1
    build:
      context: .
      dockerfile: malachite.Dockerfile
    environment:
      - CARGO_HOME=/build/malachite-node-1
      - CARGO_TARGET_DIR=/build/malachite-node-1
    volumes:
      - malachite:/malachite
      - logs:/logs
      - config:/config
      - build:/build
    networks:
      - test-network
    working_dir: /malachite
    tty: true
    stdin_open: true

  malachite-node-2:
    container_name: malachite-node-2
    build:
      context: .
      dockerfile: malachite.Dockerfile
    environment:
      - CARGO_HOME=/build/malachite-node-2
      - CARGO_TARGET_DIR=/build/malachite-node-2
    volumes:
      - malachite:/malachite
      - logs:/logs
      - config:/config
      - build:/build
    networks:
      - test-network
    working_dir: /malachite
    tty: true
    stdin_open: true

  sequencer-node-1:
    container_name: sequencer-node-1
    build:
      context: ../../../
      dockerfile: malachite/qa/starknet/sequencer.Dockerfile
    environment:
      - CARGO_HOME=/build/sequencer-node-1
      - CARGO_TARGET_DIR=/build/sequencer-node-1
    volumes:
      - sequencer:/sequencer
      - logs:/logs
      - config:/config
      - build:/build
    networks:
      - test-network
    working_dir: /sequencer
    tty: true
    stdin_open: true

  sequencer-node-2:
    container_name: sequencer-node-2
    build:
      context: ../../../
      dockerfile: malachite/qa/starknet/sequencer.Dockerfile
    environment:
      - CARGO_HOME=/build/sequencer-node-2
      - CARGO_TARGET_DIR=/build/sequencer-node-2
    volumes:
      - sequencer:/sequencer
      - logs:/logs
      - config:/config
      - build:/build
    networks:
      - test-network
    working_dir: /sequencer
    tty: true
    stdin_open: true
