volumes:

  shared:
    driver: local
    driver_opts:
      type: none
      device: ./shared
      o: bind

  malachite:
    driver: local
    driver_opts:
      type: none
      device: ../../code
      o: bind

  sequencer:
    driver: local
    driver_opts:
      type: none
      device: ../../../sequencer
      o: bind

networks:

  test-network:
    driver: bridge

services:

  malachite-node-1:
    container_name: malachite-node-1
    build:
      context: .
      dockerfile: malachite.Dockerfile
    environment:
      - CARGO_HOME=/shared/build/malachite
      - CARGO_TARGET_DIR=/shared/build/malachite
      - LOCAL_DNS=malachite-node-1
    volumes:
      - malachite:/malachite
      - shared:/shared
    networks:
      - test-network
    cap_add:
      - NET_ADMIN
    working_dir: /malachite
    tty: true
    stdin_open: true

  malachite-node-2:
    container_name: malachite-node-2
    build:
      context: .
      dockerfile: malachite.Dockerfile
    environment:
      - CARGO_HOME=/shared/build/malachite
      - CARGO_TARGET_DIR=/shared/build/malachite
      - LOCAL_DNS=malachite-node-2
    volumes:
      - malachite:/malachite
      - shared:/shared
    networks:
      - test-network
    cap_add:
      - NET_ADMIN
    working_dir: /malachite
    tty: true
    stdin_open: true

  sequencer-node-1:
    container_name: sequencer-node-1
    build:
      context: ../../../
      dockerfile: malachite/qa/starknet/sequencer.Dockerfile
    environment:
      - CARGO_HOME=/shared/build/sequencer
      - CARGO_TARGET_DIR=/shared/build/sequencer
      - LOCAL_DNS=sequencer-node-1
    volumes:
      - sequencer:/sequencer
      - shared:/shared
    networks:
      - test-network
    cap_add:
      - NET_ADMIN
    working_dir: /sequencer
    tty: true
    stdin_open: true

  sequencer-node-2:
    container_name: sequencer-node-2
    build:
      context: ../../../
      dockerfile: malachite/qa/starknet/sequencer.Dockerfile
    environment:
      - CARGO_HOME=/shared/build/sequencer
      - CARGO_TARGET_DIR=/shared/build/sequencer
      - LOCAL_DNS=sequencer-node-2
    volumes:
      - sequencer:/sequencer
      - shared:/shared
    networks:
      - test-network
    cap_add:
      - NET_ADMIN
    working_dir: /sequencer
    tty: true
    stdin_open: true
