[package]
name = "malachite-wal"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[bench]]
name = "wal"
harness = false

[features]
compression = ["dep:lz4_flex"]
force-compression = ["compression"]

[dependencies]
cfg-if = "1"
advisory-lock = "0.3.0"
bytes = "1.5.0"
crc32fast = "1.4.0"
lz4_flex = { version = "0.11.0", optional = true }

[dev-dependencies]
criterion = "0.5.1"
nix = { version = "0.29.0", features = ["signal"] }
rand = "0.8.5"
tempfile = "3.14.0"
testdir = "0.9.1"
