[package]
name = "malachite-node"
description = "Node for running the Malachite consensus engine"

version.workspace    = true
edition.workspace    = true
repository.workspace = true
license.workspace    = true
publish.workspace    = true

[dependencies]
malachite-common.workspace = true
malachite-driver.workspace = true
malachite-round.workspace  = true
malachite-vote.workspace   = true
malachite-proto.workspace  = true

derive-where = { workspace = true }
futures      = { workspace = true }
tokio        = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
prost        = { workspace = true }
prost-types  = { workspace = true }
tracing      = { workspace = true }

[dev-dependencies]
malachite-test.workspace = true
