[package]
name = "informalsystems-malachitebft-peer"
description = "Peer definition for the Malachite BFT consensus engine"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[package.metadata.docs.rs]
all-features = true

[features]
rand = ["dep:rand"]
serde = ["dep:serde"]

[dependencies]
multihash = { workspace = true, default-features = false, features = ["alloc"] }
bs58 = { workspace = true, default-features = false, features = ["alloc"] }
thiserror = { workspace = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[lints]
workspace = true
