[package]
name                 = "malachite-gossip-consensus"
version.workspace    = true
edition.workspace    = true
repository.workspace = true
license.workspace    = true
publish.workspace    = true

[lints]
workspace = true

[dependencies]
malachite-common    = { workspace = true }
malachite-metrics   = { workspace = true }
malachite-blocksync = { workspace = true }

bytes              = { workspace = true }
either             = { workspace = true }
eyre               = { workspace = true }
futures            = { workspace = true }
libp2p             = { workspace = true }
libp2p-broadcast   = { workspace = true }
seahash            = { workspace = true }
serde              = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
