[package]
name                 = "malachite-gossip-consensus"
version.workspace    = true
edition.workspace    = true
repository.workspace = true
license.workspace    = true
publish.workspace    = true

[lints]
workspace = true

[dependencies]
malachite-metrics  = { workspace = true }
malachite-proto    = { workspace = true }

blake3             = { workspace = true }
futures            = { workspace = true }
libp2p             = { workspace = true }
prost              = { workspace = true }
prost-types        = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
