[package]
name                 = "malachite-actors"
version.workspace    = true
edition.workspace    = true
repository.workspace = true
license.workspace    = true
publish.workspace    = true

[lints]
workspace = true

[dependencies]
malachite-common.workspace           = true
malachite-consensus.workspace        = true
malachite-driver.workspace           = true
malachite-gossip-consensus.workspace = true
malachite-gossip-mempool.workspace   = true
malachite-metrics.workspace          = true
malachite-node.workspace             = true
malachite-proto.workspace            = true
malachite-vote.workspace             = true

async-trait        = { workspace = true }
derive-where       = { workspace = true }
eyre               = { workspace = true }
libp2p             = { workspace = true }
ractor             = { workspace = true, features = ["async-trait"] }
tokio              = { workspace = true, features = ["full"] }
tracing            = { workspace = true }
