[package]
name = "malachite-example-channel"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
color-eyre.workspace = true
derive-where.workspace = true
eyre.workspace = true
libp2p-identity.workspace = true
rand.workspace = true
serde_json.workspace = true
sha3.workspace = true
tracing.workspace = true
tokio.workspace = true

malachite-app-channel.workspace = true
malachite-test.workspace = true
malachite-test-cli.workspace = true

[lints]
workspace = true
