[package]
name = "informalsystems-malachitebft-example-channel"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
bytes.workspace = true
color-eyre.workspace = true
derive-where.workspace = true
eyre.workspace = true
libp2p-identity.workspace = true
rand.workspace = true
serde_json.workspace = true
sha3.workspace = true
tracing.workspace = true
tokio.workspace = true

malachitebft-app-channel.workspace = true
malachitebft-test.workspace = true
malachitebft-test-cli.workspace = true

[lints]
workspace = true
