[package]
name        = "malachite-driver-test-utils"
description = "Test utilities for the `malachite-driver`"
publish     = false

version.workspace      = true
edition.workspace      = true
repository.workspace   = true
license.workspace      = true
rust-version.workspace = true


[dependencies]
malachite-common = { workspace = true }
malachite-round  = { workspace = true }
malachite-vote   = { workspace = true }
malachite-test   = { workspace = true }
malachite-driver = { workspace = true }
