name: Coverage

on:
  push:
    branches: main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 1
  CARGO_PROFILE_RELEASE_DEBUG: 1
  RUST_BACKTRACE: short
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      code: ${{ steps.filter.outputs.code }}
      specs: ${{ steps.filter.outputs.specs }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'code/**'
            specs:
              - 'specs/**'

  integration:
    name: Integration
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' || github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: code
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Quint
        run: npm install -g @informalsystems/quint
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2025-01-07 # pin to working nightly
          components: llvm-tools-preview
      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: |
          cargo llvm-cov nextest \
            --workspace \
            --exclude informalsystems-malachitebft-test-mbt \
            --ignore-filename-regex crates/cli \
            --all-features \
            --no-capture \
            --ignore-run-fail \
            --lcov \
            --output-path lcov-integration.info
      - name: Generate text report
        run: cargo llvm-cov report
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: integration-coverage
          path: code/lcov-integration.info
      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: code/target/nextest/default/junit.xml

  mbt:
    name: MBT
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' || needs.changes.outputs.specs == 'true' || github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: code
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Quint
        run: npm install -g @informalsystems/quint
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2025-01-07 # pin to working nightly
          components: llvm-tools-preview
      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov nextest -p informalsystems-malachitebft-test-mbt --all-features --lcov --output-path lcov-mbt.info
      - name: Generate text report
        run: cargo llvm-cov report
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: mbt-coverage
          path: code/lcov-mbt.info

  upload-coverage:
    name: Upload Coverage
    needs: [integration, mbt]
    runs-on: ubuntu-latest
    steps:
      - name: Download integration coverage
        uses: actions/download-artifact@v4
        with:
          name: integration-coverage
      - name: Download MBT coverage
        uses: actions/download-artifact@v4
        with:
          name: mbt-coverage
      - name: Download integration test results
        uses: actions/download-artifact@v4
        with:
          name: integration-test-results
      - name: Upload integration coverage to Codecov
        uses: codecov/codecov-action@v4
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov-integration.info
          flags: integration
          fail_ci_if_error: false
      - name: Upload MBT coverage to Codecov
        uses: codecov/codecov-action@v4
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov-mbt.info
          flags: mbt
          fail_ci_if_error: false
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: junit.xml
          flags: integration
          fail_ci_if_error: false
