name: Coverage

on:
  push:
    branches: master
    paths:
      - Code/**
  pull_request:
    paths:
      - Code/**

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: llvm-tools-preview
      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        working-directory: Code
        run: cargo llvm-cov nextest --all-features --workspace --lcov --output-path lcov.info
      - name: Generate text report
        working-directory: Code
        run: cargo llvm-cov report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: Code/lcov.info
          fail_ci_if_error: true
