name: Coverage

on:
  push:
    branches: main
    paths:
      - code/**
      - specs/quint/**
      - .github/workflows/coverage.yml
  pull_request:
    paths:
      - code/**
      - specs/quint/**
      - .github/workflows/coverage.yml

jobs:
  coverage:
    name: Integration
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: code
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install -g @informalsystems/quint
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview
      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov nextest --workspace --exclude malachite-itf --all-features --ignore-run-fail --lcov --output-path lcov.info
      - name: Generate text report
        run: cargo llvm-cov report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: code/lcov.info
          flags: integration
          fail_ci_if_error: false

  mbt-coverage:
    name: MBT
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: code
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install -g @informalsystems/quint
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview
      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov nextest -p malachite-itf --all-features --lcov --output-path lcov.info
      - name: Generate text report
        run: cargo llvm-cov report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: code/lcov.info
          flags: mbt
          fail_ci_if_error: false
