name: Coverage

on: [pull_request, push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: llvm-tools-preview
      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        working_dir: Code
        run: cargo llvm-cov nextest --all-features --workspace --lcov --output-path lcov.info
      - name: Generate text report
        working_dir: Code
        run: cargo llvm-cov report --text
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   working_dir: Code
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      #     files: lcov.info
      #     fail_ci_if_error: true
