name: Update S3 File List

on:
  push:
    branches:
      - nenad/history-file-website

jobs:
  update-file-list:
    runs-on: ubuntu-latest

    env:
      BUCKET_NAME: malachite-performance-site
      S3_PREFIX: test/
      OUTPUT_FILE: file_list.json
      BASE_URL: https://malachite-performance-site.s3.amazonaws.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: List files from S3 and generate file_list.json
        run: |
          aws s3api list-objects-v2 \
            --bucket "$BUCKET_NAME" \
            --prefix "$S3_PREFIX" \
            --query 'Contents[].Key' \
            --output json |
            jq -r '.[]' |
            grep -i '\.csv$' |
            grep -v 'file_list.json' |
            jq -R --arg base "$BASE_URL" --arg prefix "$S3_PREFIX" '{
              name: sub("^" + $prefix; ""),
              url: ($base + "/" + .)
            }' |
            jq -s . > "$OUTPUT_FILE"

      - name: Upload file_list.json to S3
        run: |
          aws s3 cp "$OUTPUT_FILE" "s3://$BUCKET_NAME/$S3_PREFIX$OUTPUT_FILE"
