name: Semver

on:
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_DEV_DEBUG: 1
  CARGO_PROFILE_RELEASE_DEBUG: 1
  RUST_BACKTRACE: short
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      code: ${{ steps.filter.outputs.code }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'code/**'

  semver-checks:
    name: Detect semver violations
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Necessary to post comments on PRs
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache-workspaces: "code"
      - name: Install cargo-semver-checks
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-semver-checks
      - name: Check semver
        id: semver-check
        run: |
          # Run the checks and capture output
          output_file="semver_check_output.txt"
          if cargo semver-checks \
            --package informalsystems-malachitebft-core-types \
            --package informalsystems-malachitebft-core-consensus \
            --package informalsystems-malachitebft-engine \
            --package informalsystems-malachitebft-app \
            --package informalsystems-malachitebft-app-channel \
            --package informalsystems-malachitebft-codec \
            --package informalsystems-malachitebft-sync \
            --package informalsystems-malachitebft-wal \
            --package informalsystems-malachitebft-metrics \
            --manifest-path code/Cargo.toml \
            > "$output_file" 2>&1; then
            echo "Semver check passed"
            echo "has_violations=false" >> $GITHUB_OUTPUT
          else
            echo "Semver check failed"
            echo "has_violations=true" >> $GITHUB_OUTPUT
            cat "$output_file"
          fi

          # Extract package name and required version bump from output
          if grep -q "semver requires new major version" "$output_file"; then
            echo "version_bump=major" >> $GITHUB_OUTPUT
            # Try to extract the affected package(s)
            affected_packages=$(grep -o "Checking [^ ]* " "$output_file" | grep -v "no semver update required" | sed 's/Checking //g' | tr '\n' ',' | sed 's/,$//')
            echo "affected_packages=$affected_packages" >> $GITHUB_OUTPUT
          elif grep -q "semver requires new minor version" "$output_file"; then
            echo "version_bump=minor" >> $GITHUB_OUTPUT
            affected_packages=$(grep -o "Checking [^ ]* " "$output_file" | grep -v "no semver update required" | sed 's/Checking //g' | tr '\n' ',' | sed 's/,$//')
            echo "affected_packages=$affected_packages" >> $GITHUB_OUTPUT
          else
            echo "version_bump=unknown" >> $GITHUB_OUTPUT
            echo "affected_packages=unknown" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true
      - name: Post comment on PR
        if: steps.semver-check.outputs.has_violations == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const versionBump = '${{ steps.semver-check.outputs.version_bump }}';
            const affectedPackages = '${{ steps.semver-check.outputs.affected_packages }}';

            let message = '## ⚠️ Semver Violation Detected ⚠️\n\n';
            message += 'This PR introduces breaking changes that violate semantic versioning rules.\n\n';

            if (versionBump === 'major') {
              message += '### Required Action\n\n';
              message += 'You need to either:\n';
              message += '1. **Revert the breaking changes** to maintain backward compatibility, OR\n';
              message += '2. Take all of the following steps:\n';
              message += '   - **Update the version in Cargo.toml** to a new major version (e.g., from `1.2.3-pre` to `2.0.0-pre`)\n';
              message += '   - **Document the breaking changes** in `BREAKING_CHANGES.md` with details about what changed and how users should adapt\n\n';
              message += '### Affected Package(s)\n\n';
              message += affectedPackages !== 'unknown' ? `- ${affectedPackages.replace(/,/g, '\n- ')}\n\n` : 'Could not determine specific packages.\n\n';
            } else if (versionBump === 'minor') {
              message += '### Required Action\n\n';
              message += 'You need to either:\n';
              message += '1. **Revert the changes** if they were not intended, OR\n';
              message += '2. Take all of the following steps:\n';
              message += '   - **Update the version in Cargo.toml** to a new major version (e.g., from `0.2.3-pre` to `0.3.0-pre`)\n';
              message += '   - **Document the breaking changes** in `BREAKING_CHANGES.md` with details about what changed and how users should adapt\n\n';
              message += '### Affected Package(s)\n\n';
              message += affectedPackages !== 'unknown' ? `- ${affectedPackages.replace(/,/g, '\n- ')}\n\n` : 'Could not determine specific packages.\n\n';
            } else {
              message += '### Required Action\n\n';
              message += 'You need to either:\n';
              message += '1. **Revert the changes** if they were not intended, OR\n';
              message += '2. Take all of the following steps:\n';
              message += '   - **Update the version in Cargo.toml** to a new version, depending on the type of semver violation\n';
              message += '   - **Document the breaking changes** in `BREAKING_CHANGES.md` with details about what changed and how users should adapt\n\n';
            }

            message += '### Breaking Changes Documentation\n\n';
            message += 'If you decide to keep the breaking changes, please make sure to:\n';
            message += '- Update BREAKING_CHANGES.md with a detailed explanation of the changes\n';
            message += '- Include information about how users should migrate their code\n';
            message += '- Specify which version introduces these changes\n\n';

            message += 'For more information on semantic versioning in Rust, please consult the [Rust API Guidelines](https://rust-lang.github.io/api-guidelines/necessities) and [Cargo\'s SemVer compatibility rules](https://doc.rust-lang.org/cargo/reference/semver.html).';

            // Get all comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // Look for an existing semver violation comment from this workflow
            const botComment = comments.find(comment =>
              comment.user.login === 'github-actions[bot]' &&
              comment.body.includes('Semver Violation Detected')
            );

            if (botComment) {
              // Update the existing comment
              await github.rest.issues.updateComment({
                comment_id: botComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
              console.log(`Updated existing comment ID ${botComment.id}`);
            } else {
              // Create a new comment
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
              console.log('Created new comment');
            }
      - name: Fail workflow if semver check failed
        if: steps.semver-check.outputs.has_violations == 'true'
        run: |
          echo "::error::Semver check failed. Please see PR comments for details on how to fix this issue."
          exit 1
